In [23]:
import numpy as np

In [24]:
import pandas as pd

In [25]:
arr=np.array([[2,2,-2],[2,-1,4],[-2,4,-1]])

In [26]:
arr

array([[ 2,  2, -2],
       [ 2, -1,  4],
       [-2,  4, -1]])

In [27]:
eigenvalues=np.linalg.eigvals(arr)
eigenvalues

array([ 3., -6.,  3.])

In [41]:
ev,evector=np.linalg.eigh(arr)

In [42]:
ev

array([-6.,  3.,  3.])

In [43]:
evector=evector

In [44]:
p=evector

In [45]:
p_1=np.linalg.inv(p)


In [46]:
a=np.dot(p_1,arr)

In [47]:
answer=np.dot(a,p)

In [48]:
answer

array([[-6.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16,  3.00000000e+00,  0.00000000e+00],
       [-2.22044605e-15,  1.11022302e-16,  3.00000000e+00]])

In [49]:
np.round_(answer,2)

array([[-6.,  0.,  0.],
       [-0.,  3.,  0.],
       [-0.,  0.,  3.]])